### ISSUE TITLE
预训练模型

### ISSUE THREAD

**Issue by cxzyoung** [WxTu/DFCN#1]
怎么得到预训练模型，几个py文件里面没有看到关于预训练的文件

**Comment by lxhello** [comment]
我也很好奇，请问你最后找到了吗

**Comment by 1862549** [comment]
请问您们复现出来了预训练文件了吗？我也很想知道

**Comment by Breeze-J** [comment]
有人复现出来了吗？

**Comment by WxTu** [comment]
Thank you for your attention! We have uploaded the model pre-training demo. Kindly take a moment to review it.

**Comment by 1862549** [comment]
> 有人复现出来了吗？

没，作者刚刚评论说上传了模型预训练演示，我进来没找见，请问你找见了吗？

**Comment by 1862549** [comment]
> Thank you for your attention! We have uploaded the model pre-training demo. Kindly take a moment to review it.

Hello, I haven't found the pre trained model code. Could you please provide a link if it's convenient. Thanks

**Comment by WxTu** [comment]
> > Thank you for your attention! We have uploaded the model pre-training demo. Kindly take a moment to review it.
> 
> Hello, I haven't found the pre trained model code. Could you please provide a link if it's convenient. Thanks

**Comment by WxTu** [comment]
> > Thank you for your attention! We have uploaded the model pre-training demo. Kindly take a moment to review it.
> 
> Hello, I haven't found the pre trained model code. Could you please provide a link if it's convenient. Thanks

> Please check the Preparation section in README.

**Comment by 1862549** [comment]
> > > Thank you for your attention! We have uploaded the model pre-training demo. Kindly take a moment to review it.
> > 
> > 
> > Hello, I haven't found the pre trained model code. Could you please provide a link if it's convenient. Thanks
> 
> > Please check the Preparation section in README.

I found it. Thank you
